defaults:
    - override hydra/launcher: submitit_local

# environment
task: Asterix
obs: rgb
task_platform: atari
has_done: true

#only for atari
gray_scale: false
obs_to_string: true
n_skip: 4
max_episode_steps: 108_000
episode_life: true
clip_rewards: true
resize: 96
noop: 30
action: multistep_randomshooting #multistep_randomshooting #discrete, continuous, mcts
discount: 0.997
pretrain_steps: 200
downsample: false
reduced_channels: 16
video: true
replay_ratio: 8
reset_interval: 40_000
reset_layers: 2
reset_percent: 0.8

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 10000

# training
steps: 120_000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
# lr: 0.2
# optimizer: sgd
lr: 3e-4
optimizer: adam
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
exp_name: mcts_muzero
data_dir: ???
device: cuda:1

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4
target_entropy: 0.89
autotune: false

# critic
num_bins: 51
vmin: -6
vmax: +6

# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: official_atari
wandb_entity: yux076-ucsd
wandb_silent: false
enable_wandb: false
save_csv: false

# misc
save_video: false #should be solved in atari
save_agent: false
seed: 6

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???
# speedups
compile: False

#mcts:
num_simulations: 50       
c_2: 19652.                 # for muzero
c_1: 1.25                  # for muzero
value_minmax_delta: 1e-6      
vis: [log]       
dirichlet_alpha: 0.3          
explore_frac: 0.25            
mcts_temperature: 1.0    
reanalyze: false